-- Seed Data for LuminaLib Book Library Application

INSERT INTO books (title, author, isbn, genre, description, cover_url, status, rating, review, notes, page_count, date_read, is_favorite, open_library_key)
VALUES 
(
    'Dune', 
    'Frank Herbert', 
    '9780441172719', 
    'Science Fiction', 
    'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the spice melange.', 
    'https://covers.openlibrary.org/b/isbn/9780441172719-L.jpg', 
    'Read', 
    5, 
    'A masterpiece of world-building and political intrigue. The depth of ecology, religion, and philosophy woven into a sci-fi epic is unmatched.', 
    'Pay attention to the Bene Gesserit prophecies and the Litany Against Fear.', 
    688, 
    '2026-02-15', 
    TRUE, 
    '/works/OL893415W'
),
(
    'Atomic Habits', 
    'James Clear', 
    '9780735211292', 
    'Self-Help', 
    'An easy and proven way to build good habits and break bad ones. James Clear reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.', 
    'https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg', 
    'Read', 
    5, 
    'Extremely practical framework for habit building. The focus on identity-based habits rather than outcome-based goals was a game-changer.', 
    'Key take-away: You do not rise to the level of your goals. You fall to the level of your systems.', 
    320, 
    '2026-01-10', 
    TRUE, 
    '/works/OL17930368W'
),
(
    'Project Hail Mary', 
    'Andy Weir', 
    '9780593135204', 
    'Science Fiction', 
    'Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself will perish.', 
    'https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg', 
    'Read', 
    5, 
    'Pure scientific problem-solving joy! Rocky is one of the best alien companion characters in modern fiction. Highly recommended audio or print.', 
    'Fascinating depiction of interstellar physics and language learning.', 
    496, 
    '2026-03-01', 
    TRUE, 
    '/works/OL21634731W'
),
(
    '1984', 
    'George Orwell', 
    '9780451524935', 
    'Dystopian', 
    'Winston Smith wrestles with oppression in Oceania, a place where the Party scrutinizes human actions with an ever-watchful eye.', 
    'https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg', 
    'Read', 
    4, 
    'Chillingly prophetic. The concepts of Newspeak and Doublethink are incredibly relevant.', 
    'Rereading after several years highlights its psychological depth.', 
    328, 
    '2025-11-20', 
    FALSE, 
    '/works/OL1168083W'
),
(
    'The Hobbit', 
    'J.R.R. Tolkien', 
    '9780547928227', 
    'Fantasy', 
    'Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely traveling further than the pantry of his hobbit-hole in Bag End.', 
    'https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg', 
    'Reading', 
    4, 
    'Delightful fantasy adventure. Tolkien writes with such warmth and mythical charm.', 
    'Currently at Chapter 9: Barrels Out of Bond.', 
    310, 
    NULL, 
    TRUE, 
    '/works/OL262758W'
),
(
    'Deep Work', 
    'Cal Newport', 
    '9781455586691', 
    'Productivity', 
    'Rules for focused success in a distracted world. Deep work is the ability to focus without distraction on a cognitively demanding task.', 
    'https://covers.openlibrary.org/b/isbn/9781455586691-L.jpg', 
    'Want to Read', 
    0, 
    NULL, 
    'Recommended by colleagues for improving focus during long programming sessions.', 
    304, 
    NULL, 
    FALSE, 
    '/works/OL17358797W'
),
(
    'Clean Code', 
    'Robert C. Martin', 
    '9780132350884', 
    'Technology', 
    'Even bad code can function. But if code isn\'t clean, it can bring a development organization to its knees.', 
    'https://covers.openlibrary.org/b/isbn/9780132350884-L.jpg', 
    'Read', 
    4, 
    'Essential reading for developers. Mind naming conventions, small single-responsibility functions, and meaningful comments.', 
    'Refactored several backend services after reading.', 
    464, 
    '2025-08-14', 
    FALSE, 
    '/works/OL15186000W'
);
